# this is a required setting for this theme to appear on https://themes.gohugo.io/
# change this to a value appropriate for you; if your site is served from a subdirectory
# set it like "https://example.com/mysite/"
baseURL = "https://www.ha-box.xyz/"

# required value to serve this page from a webserver AND the file system;
# if you don't want to serve your page from the file system, you can also set this value
# to false
relativeURLs = true # true -> rewrite all site-relative URLs (those with a leading slash) to be relative to the current content
# if you set uglyURLs to false, this theme will append 'index.html' to any page bundle link
# so your site can be also served from the file system; if you don't want that,
# set disableExplicitIndexURLs=true in the [params] section
uglyURLs = false    # true -> basic/index.html -> basic.html

# the directory where Hugo reads the themes from; this is specific to your
# installation and most certainly needs be deleted or changed
#themesdir = "../.."
# yeah, well, obviously a mandatory setting for your site, if you want to
# use this theme ;-)
theme = "hugo-theme-relearn"

# make sure your defaultContentLanguage is the first one in the [languages]
# array below, as the theme needs to make assumptions on it
defaultContentLanguage = "zh-cn"
# if you want to get rrrid o' ourrr pirrrates nonsense uncomment th' next line
# disableLanguages = ['pir']

# the site's title of this showcase; you should change this ;-)
title = "HaBox 技术支持站"

# Don't use any auto-generated summaries
summaryLength = 10

[outputs]
  # add `search` to the home to support Lunr search; This is a mandatory setting
  # for the side wide search functionality
  # add `searchpage` to the home to create a dedicated searchpage
  # add `print` to home, section and page to activate the feature to print whole
  # chapters
  home = ["html", "rss", "print", "search", "searchpage"]
  section = ["html", "rss", "print"]
  page = ["html", "rss", "print"]


[params]
  # Demo setting for displaying the siteparam shortcode the docs.
  #siteparam.test.text = "A **nested** option <b>with</b> formatting"
  # Extension to the image effects only for the docs.
  #imageEffects.bg-white = true
